### variable

@session = fa5c10eb-7d20-48fb-93ea-43f42de3047f
@localhost = http://localhost:8080

### check backend app

GET {{localhost}}/ping

#### test connect db

POST {{localhost}}/connect/test
Content-Type: application/json

{
  "type": "POSTGRES",
  "host": "localhost",
  "port": 5432,
  "database": "postgres",
  "username": "postgres",
  "password": "123456"
}

### create session

POST {{localhost}}/connect/create
Content-Type: application/json

{
  "type": "POSTGRES",
  "host": "localhost",
  "port": 5432,
  "database": "postgres",
  "username": "postgres",
  "password": "123456"
}

### close session

DELETE {{localhost}}/connect/{{session}}

### get list sessions

GET {{localhost}}/connect/sessions

### query

POST {{localhost}}/query
Content-Type: application/json

# {
#   "sessionId": "{{session}}",
#   "sql": "create table users(id SERIAL, name varchar(100))"
# }

# {
#   "sessionId": "{{session}}",
#   "sql": "insert into users(name) values ('Alice')"
# }

{
  "sessionId": "{{session}}",
  "sql": "select * from users"
}

### get all table name

GET {{localhost}}/metadata/tables/{{session}}

### get column of table

GET {{localhost}}/metadata/columns/{{session}}/users

### saved connection list

GET {{localhost}}/saved-connections

### get by id saved connection

GET {{localhost}}/saved-connections/1
