### check backend app

GET http://localhost:8080/ping

#### test connect db

POST http://localhost:8080/connect/test
Content-Type: application/json

{
  "type": "POSTGRES",
  "host": "localhost",
  "port": 5432,
  "database": "postgres",
  "username": "postgres",
  "password": "123456"
}

### create session

POST http://localhost:8080/connect/create
Content-Type: application/json

{
  "type": "POSTGRES",
  "host": "localhost",
  "port": 5432,
  "database": "postgres",
  "username": "postgres",
  "password": "123456"
}

### close session

DELETE http://localhost:8080/connect/04c220a9-402b-4b8d-9af0-d6e417df5498

### get list sessions

GET http://localhost:8080/connect/sessions

### query

POST http://localhost:8080/query
Content-Type: application/json

# {
#   "sessionId": "1e7a9ed2-f385-4214-a59b-9a7521cfa0a1",
#   "sql": "create table users(id SERIAL, name varchar(100))"
# }

# {
#   "sessionId": "1e7a9ed2-f385-4214-a59b-9a7521cfa0a1",
#   "sql": "insert into users(name) values ('Alice')"
# }

{
  "sessionId": "1e7a9ed2-f385-4214-a59b-9a7521cfa0a1",
  "sql": "select * from users"
}

###

GET http://localhost:8080/metadata/tables/94a07ae4-0533-4238-a00a-131cbcefd10e
